# Generated by Django 3.2.12 on 2022-03-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModelBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_char', models.CharField(max_length=100)),
                ('attr_int', models.IntegerField()),
                ('attr_bool', models.BooleanField(default=True)),
                ('attr_choices', models.CharField(choices=[('choice_1', 'Choice 1'), ('choice_2', 'Choice 2')], default='choice_1', max_length=100)),
                ('attr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.samplemodelbase')),
            ],
            options={
                'verbose_name': 'sample',
                'verbose_name_plural': 'samples',
                'ordering': ['attr_char'],
            },
        ),
    ]
